name: Daily AI News Update

on:
  schedule:
    # 每天凌晨3点运行 (UTC时间)
    - cron: '0 3 * * *'
  
  # 允许手动触发工作流
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 设置Node.js环境
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: 安装依赖
        run: |
          npm install axios cheerio

      - name: 更新AI新闻数据
        run: |
          chmod +x github_automation/fetch_news.sh
          ./github_automation/fetch_news.sh
      
      - name: 构建网站
        run: |
          cd ai-news-app
          npm install
          npm run build
          cp -r dist/* ../dist/
          cp ../news_data.json dist/
      
      - name: 部署到GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          
      - name: 提交更新的新闻数据
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add news_data.json
          git commit -m "自动更新: $(date +'%Y-%m-%d') AI新闻数据" || echo "没有变更需要提交"
          git push
